import type { Metadata } from "next";
import { Roboto } from "next/font/google";
// import { Inter } from 'next/font/google';
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { Toaster } from "react-hot-toast";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  variable: "--font-roboto",
  display: "swap",
});
// const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${roboto.variable}`} suppressHydrationWarning>
      <body className="font-roboto overflow-x-hidden">
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem={true}
        >
          <Toaster
            position="top-right"
            toastOptions={{
              duration: 5000,
              style: {
                background: "transparent",
                boxShadow: "none",
              },
            }}
          />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
